//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NAPOLEONEntities : DbContext
    {
        public NAPOLEONEntities()
            : base("name=NAPOLEONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_DET_ServicioSitio> tbl_DET_ServicioSitio { get; set; }
        public DbSet<tbl_ConfigSitio> tbl_ConfigSitio { get; set; }
        public DbSet<tbl_DET_Estudio> tbl_DET_Estudio { get; set; }
    
        public virtual ObjectResult<stp_getEstudiosEnviar_Result> stp_getEstudiosEnviar(Nullable<int> id_Sitio)
        {
            var id_SitioParameter = id_Sitio.HasValue ?
                new ObjectParameter("id_Sitio", id_Sitio) :
                new ObjectParameter("id_Sitio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getEstudiosEnviar_Result>("stp_getEstudiosEnviar", id_SitioParameter);
        }
    }
}
