//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DET_Estudio_AUD
    {
        public int intDetAUD_EstudioID { get; set; }
        public Nullable<int> intDetEstudioID { get; set; }
        public Nullable<int> TIPOMOV_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> intEstatusID { get; set; }
        public string vchNameFile { get; set; }
        public Nullable<int> intSizeFile { get; set; }
        public string vchPathFile { get; set; }
    
        public virtual tbl_DET_Estudio tbl_DET_Estudio { get; set; }
    }
}
