//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Extensiones
    {
        public int id { get; set; }
        public string vchClave { get; set; }
        public string vchDescripcion { get; set; }
        public string vchValor { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
    }
}
