//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_REL_SitioModalidad
    {
        public int intREL_SitioModID { get; set; }
        public Nullable<int> id_Sitio { get; set; }
        public Nullable<int> intModalidadID { get; set; }
        public Nullable<int> intSecuencia { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
    
        public virtual tbl_CAT_Modalidad tbl_CAT_Modalidad { get; set; }
        public virtual tbl_ConfigSitio tbl_ConfigSitio { get; set; }
    }
}
