//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DET_Estudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DET_Estudio()
        {
            this.tbl_DET_Estudio_AUD = new HashSet<tbl_DET_Estudio_AUD>();
        }
    
        public int intDetEstudioID { get; set; }
        public Nullable<int> intEstudioID { get; set; }
        public Nullable<int> intEstatusID { get; set; }
        public string vchNameFile { get; set; }
        public Nullable<int> intSizeFile { get; set; }
        public string vchPathFile { get; set; }
        public string vchStudyInstanceUID { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitFileComplete { get; set; }
        public string vchPathServidor { get; set; }
    
        public virtual tbl_CAT_Estatus tbl_CAT_Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DET_Estudio_AUD> tbl_DET_Estudio_AUD { get; set; }
        public virtual tbl_MST_Estudio tbl_MST_Estudio { get; set; }
    }
}
