//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SenderFeed2SCU.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_PrioridadEstudio
    {
        public int intPrioridadID { get; set; }
        public Nullable<int> intEstudioID { get; set; }
        public Nullable<bool> bitUrgente { get; set; }
        public Nullable<int> intSecuencia { get; set; }
        public string vchusuarioSol { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitAtendido { get; set; }
        public Nullable<System.DateTime> datAtendido { get; set; }
    
        public virtual tbl_MST_Estudio tbl_MST_Estudio { get; set; }
    }
}
